[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.0"
name = "iSSL"

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "methods*", "scripts*", "tests*"]