# -- MAE --
mask_ratio: 0.75
seed: 42
drop_path_p: 0.2
use_swiglu: False
use_bias: True

# -- image stuff --
input_size: [224, 224]
patch_kernel: [14, 14]
patch_stride: [14, 14]
patch_padding: [0, 0]

batch_size: 256 
num_epochs: 400 
warmup_epochs: 40
weight_decay: 0.05
muon_mode: "match_rms_adamw"
lr_adamw: 8e-4
lr_muon: 8e-4
adamw_betas: [0.9, 0.95]
# # if original
# muon_mode: "original"
# lr_adamw: 1e-4
# lr_muon: 0.01
grad_clip: -1
grad_accum: 1
is_restore: false
checkpoint_init_dir: ""

# -- Logging --
checkpoint_dir: "output/checkpoints/MAE/"
every_n_checkpoint: 1

every_n_epoch: 1
every_n_step: 10
