program: scripts/probe_MAE_adam.py
project: probe_MAE
entity: hachoj-university-of-florida
method: grid
metric:
  name: epoch/val_top1
  goal: maximize

parameters:
  train.lr:
    values: [1e-2, 5e-3, 2e-3, 1e-3, 5e-4, 2e-4, 1e-4, 5e-5, 2e-5, 1e-5]
  train.weight_decay:
    values: [5e-2, 1e-3, 5e-4]

command:
  - ${env}
  - torchrun
  - --standalone
  - --nproc_per_node=1
  - ${program}
  - ${args_no_hyphens}
