program: scripts/probe_MAE.py
method: grid
metric:
  name: epoch/val_top1
  goal: maximize

parameters:
  lr:
    values: [1e-5, 2e-5, 5e-5, 1e-4, 2e-4, 5e-4, 1e-3, 2e-3, 5e-3, 1e-2]
  wd:
    values: [0.0, 0.05, 0.1]

command:
  - ${env}
  - torchrun
  - --standalone
  - --nproc_per_node=1
  - ${program}
  - train.lr_adamw=${lr}
  - train.lr_muon=${lr}
  - train.weight_decay=${wd}